import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const speciesPath = path.join(__dirname, '../src/data/species.json')
const species = JSON.parse(fs.readFileSync(speciesPath, 'utf8'))
/** "Delight" on its own line is treated as Banksia spinulosa 'Honeyeater Delight'. */
const NEW_PLANTS = [
  {
    scientific_name: "Banksia 'Birdsong'",
    common_name: 'Birdsong Banksia',
    genus: 'Banksia',
    pretreatment: 'None Required (nursery plant / cutting-grown cultivar)',
    germination: 'Usually sold as tube stock. Softwood cuttings in coarse sand-perlite under mist. Keep warm.',
    growth_rate: 'Moderate',
    mature_height: '1m - 1.5m',
    mature_width: '1m - 1.5m',
    foliage: 'Fine-textured green banksia foliage, compact shrub habit.',
    flowers: 'Golden to amber cylindrical flower spikes, bird-attracting.',
    flowering_time: 'Autumn – Winter',
    soil_preference: 'Well-drained sandy loam; avoid heavy wet clay',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Garden cultivar; not a wild conservation taxon.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Banksia_spinulosa.jpg',
  },
  {
    scientific_name: 'Banksia ericifolia (dwarf form)',
    common_name: 'Dwarf Heath-leaved Banksia',
    genus: 'Banksia',
    pretreatment: 'None Required (or smoke / hot water for seed of species)',
    germination: 'Species seed: sow on surface of sandy mix, keep moist. Cultivar usually grown from cuttings.',
    growth_rate: 'Moderate',
    mature_height: '1m - 2m',
    mature_width: '1m - 2m',
    foliage: 'Fine heath-like linear leaves, dense dwarf shrub.',
    flowers: 'Orange to red cylindrical spikes.',
    flowering_time: 'Autumn – Winter (Apr - Aug)',
    soil_preference: 'Acid sandy loam, well drained',
    frost_tolerance: 'Moderate (-5°C)',
    drought_tolerance: 'High',
    conservation_status: 'Least Concern',
    conservation_locale: 'NSW',
    conservation_description: 'Species secure in coastal heath; dwarf forms are garden selections.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Banksia_ericifolia_flower.jpg',
  },
  {
    scientific_name: 'Banksia marginata (bright-flower form)',
    common_name: 'Silver Banksia (bright flowers)',
    genus: 'Banksia',
    pretreatment: 'None Required (smoke helpful for seed)',
    germination: 'Sow seed on sandy surface mix; light cover. Cultivars usually cutting-grown.',
    growth_rate: 'Moderate',
    mature_height: '1m - 5m',
    mature_width: '1m - 4m',
    foliage: 'Oblong leaves with silver undersides; variable shrub to small tree.',
    flowers: 'Bright yellow cylindrical spikes.',
    flowering_time: 'Summer – Autumn',
    soil_preference: 'Well-drained sandy or loamy soils; adaptable',
    frost_tolerance: 'High (-8°C)',
    drought_tolerance: 'High',
    conservation_status: 'Least Concern',
    conservation_locale: 'SE Australia',
    conservation_description: 'Widespread in south-eastern Australia; bright-flower forms selected for gardens.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Banksia_marginata.jpg',
  },
  {
    scientific_name: "Banksia spinulosa 'Honeyeater Delight'",
    common_name: 'Honeyeater Delight Banksia',
    genus: 'Banksia',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Propagate from cuttings. Species seed possible with smoke treatment.',
    growth_rate: 'Moderate',
    mature_height: '1m - 1.5m',
    mature_width: '1m - 1.5m',
    foliage: 'Fine green toothed leaves, compact rounded shrub.',
    flowers: 'Gold to bronze flower spikes, excellent for honeyeaters.',
    flowering_time: 'Autumn – Winter',
    soil_preference: 'Well-drained sandy loam; low phosphorus native mix',
    frost_tolerance: 'Moderate (-5°C)',
    drought_tolerance: 'High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Popular compact Banksia spinulosa cultivar for smaller gardens.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Banksia_spinulosa.jpg',
  },
  {
    scientific_name: "Callistemon viminalis 'Little John'",
    common_name: 'Little John Bottlebrush',
    genus: 'Callistemon',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Usually cutting-grown. Species seed sown on surface of sandy mix.',
    growth_rate: 'Moderate',
    mature_height: '0.8m - 1.2m',
    mature_width: '0.8m - 1.2m',
    foliage: 'Dense blue-green narrow leaves, compact dwarf habit.',
    flowers: 'Deep red bottlebrush spikes.',
    flowering_time: 'Spring – Summer (repeat flushes)',
    soil_preference: 'Moist well-drained loam; tolerates clay if not waterlogged',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Widely grown dwarf bottlebrush cultivar (also listed under Melaleuca viminalis).',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Callistemon_viminalis_flowers.jpg',
  },
  {
    scientific_name: "Eremophila glabra 'Kalbarri Carpet'",
    common_name: 'Kalbarri Carpet Emu Bush',
    genus: 'Eremophila',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Cuttings preferred. Species seed often needs leaching / smoke.',
    growth_rate: 'Moderate',
    mature_height: '0.2m - 0.4m',
    mature_width: '1.5m - 3m',
    foliage: 'Grey-green prostrate foliage, dense groundcover.',
    flowers: 'Orange to red tubular flowers along stems.',
    flowering_time: 'Winter – Spring (sporadic year-round in mild climates)',
    soil_preference: 'Very well-drained sandy or gravelly soil; open sunny site',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'Extremely High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection (WA affinity)',
    conservation_description: 'Prostrate Eremophila glabra selection; excellent dry-garden groundcover.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Eremophila_glabra.jpg',
  },
  {
    scientific_name: "Hakea 'Burrendong Beauty'",
    common_name: 'Burrendong Beauty Hakea',
    genus: 'Hakea',
    pretreatment: 'None Required (cutting-grown hybrid)',
    germination: 'Cutting-grown. Related species seed: sow in sandy mix after light scarification if hard.',
    growth_rate: 'Moderate',
    mature_height: '1m - 2m',
    mature_width: '1.5m - 2.5m',
    foliage: 'Needle-like grey-green foliage, spreading shrub.',
    flowers: 'Pink to mauve clustered flowers, bird-attracting.',
    flowering_time: 'Winter – Spring',
    soil_preference: 'Well-drained sandy loam or gravel; full sun',
    frost_tolerance: 'High (-6°C)',
    drought_tolerance: 'High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Garden hybrid (often linked to H. bakeriana × H. sericea lines); tough ornamental.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Hakea_sericea_flowers.jpg',
  },
  {
    scientific_name: 'Hakea bucculenta',
    common_name: 'Red Pokers',
    genus: 'Hakea',
    pretreatment: 'None Required',
    germination: 'Sow in free-draining sandy native mix; cover lightly. Keep moist until established.',
    growth_rate: 'Moderate',
    mature_height: '2m - 4m',
    mature_width: '1.5m - 3m',
    foliage: 'Long linear green leaves; upright shrub.',
    flowers: 'Striking orange-red poker-like flower spikes.',
    flowering_time: 'Winter – Spring (Jul - Oct)',
    soil_preference: 'Well-drained sand or gravelly loam; sunny position',
    frost_tolerance: 'Moderate (-3°C)',
    drought_tolerance: 'High',
    conservation_status: 'Least Concern',
    conservation_locale: 'WA',
    conservation_description: 'Western Australian species widely grown in gardens for spectacular blooms.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Hakea_bucculenta.jpg',
  },
  {
    scientific_name: "Leptospermum 'Crimson Cascade'",
    common_name: 'Crimson Cascade Tea-tree',
    genus: 'Leptospermum',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Cuttings preferred. Species seed: surface sow on fine mix.',
    growth_rate: 'Moderate',
    mature_height: '0.5m - 1.5m',
    mature_width: '1m - 2m',
    foliage: 'Fine weeping green foliage; cascading habit.',
    flowers: 'Deep crimson to red tea-tree flowers along arching stems.',
    flowering_time: 'Spring',
    soil_preference: 'Moist well-drained acidic loam; mulch well',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Ornamental weeping tea-tree cultivar for banks and pots.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Leptospermum_scoparium.jpg',
  },
  {
    scientific_name: 'Melaleuca decussata (dwarf form)',
    common_name: 'Dwarf Totem Poles / Cross-leaf Honey-myrtle',
    genus: 'Melaleuca',
    pretreatment: 'None Required',
    germination: 'Surface sow fine seed on sandy mix; keep evenly moist. Dwarf forms often cutting-grown.',
    growth_rate: 'Moderate',
    mature_height: '0.5m - 1.5m',
    mature_width: '1m - 2m',
    foliage: 'Tiny opposite cross-arranged leaves; dense dwarf shrub.',
    flowers: 'Mauve to lilac bottlebrush-like clusters.',
    flowering_time: 'Spring – Summer',
    soil_preference: 'Moist to well-drained loam; tolerates heavier soils than many natives',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Least Concern',
    conservation_locale: 'SA / VIC',
    conservation_description: 'Species common in south-eastern Australia; dwarf forms selected for smaller gardens.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Melaleuca_decussata.jpg',
  },
  {
    scientific_name: "Pimelea ferruginea 'Bonne Petite'",
    common_name: 'Bonne Petite Rice Flower',
    genus: 'Pimelea',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Soft tip cuttings in coarse mix under humidity. Species seed can be slow.',
    growth_rate: 'Moderate',
    mature_height: '0.4m - 0.8m',
    mature_width: '0.5m - 1m',
    foliage: 'Small neat opposite leaves; compact rounded shrub.',
    flowers: 'Bright pink dense flower heads.',
    flowering_time: 'Spring',
    soil_preference: 'Well-drained sandy loam; excellent drainage essential',
    frost_tolerance: 'Moderate (-3°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection (WA affinity)',
    conservation_description: 'Compact pink Pimelea ferruginea selection for rockeries and pots.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Pimelea_ferruginea.jpg',
  },
  {
    scientific_name: "Pimelea ferruginea 'Alba'",
    common_name: 'White Rice Flower',
    genus: 'Pimelea',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Cuttings preferred in free-draining mix.',
    growth_rate: 'Moderate',
    mature_height: '0.5m - 1m',
    mature_width: '0.6m - 1.2m',
    foliage: 'Small dark green opposite leaves; tidy shrub.',
    flowers: 'Creamy white dense terminal flower heads.',
    flowering_time: 'Spring',
    soil_preference: 'Well-drained sandy or gravelly soil; full sun',
    frost_tolerance: 'Moderate (-3°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection (WA affinity)',
    conservation_description: 'White-flowered form of Pimelea ferruginea for contrast plantings.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Pimelea_ferruginea.jpg',
  },
  {
    scientific_name: "Scaevola aemula 'Mauve Clusters'",
    common_name: 'Mauve Clusters Fan Flower',
    genus: 'Scaevola',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Tip cuttings root readily. Species seed possible but cultivars are cutting-grown.',
    growth_rate: 'Fast',
    mature_height: '0.2m - 0.4m',
    mature_width: '0.6m - 1.2m',
    foliage: 'Bright green toothed leaves; spreading groundcover.',
    flowers: 'Mauve fan-shaped flowers in dense clusters.',
    flowering_time: 'Spring – Autumn (long flowering)',
    soil_preference: 'Well-drained potting / sandy loam; regular light moisture',
    frost_tolerance: 'Low (0°C)',
    drought_tolerance: 'Moderate',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Popular fan-flower cultivar for borders, baskets and mass planting.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Scaevola_aemula.jpg',
  },
  {
    scientific_name: 'Scleranthus biflorus',
    common_name: 'Twin-flowered Knawel / Cushion Bush',
    genus: 'Scleranthus',
    pretreatment: 'None Required',
    germination: 'Sow fine seed on surface of sandy mix; keep lightly moist. Also divides easily.',
    growth_rate: 'Slow to Moderate',
    mature_height: '0.05m - 0.15m',
    mature_width: '0.3m - 1m',
    foliage: 'Bright green moss-like cushion of tiny leaves.',
    flowers: 'Inconspicuous tiny greenish twin flowers.',
    flowering_time: 'Spring – Summer',
    soil_preference: 'Moist well-drained sandy loam; part shade to sun',
    frost_tolerance: 'High (-8°C)',
    drought_tolerance: 'Low to Moderate',
    conservation_status: 'Least Concern',
    conservation_locale: 'SE Australia / TAS',
    conservation_description: 'Secure alpine and cool temperate native; valued as a living mulch / rockery cushion.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Scleranthus_biflorus.jpg',
  },
  {
    scientific_name: "Thryptomene 'Supernova'",
    common_name: 'Supernova Thryptomene',
    genus: 'Thryptomene',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Semi-hardwood cuttings in coarse sand. Species seed fine and slow.',
    growth_rate: 'Moderate',
    mature_height: '0.8m - 1.2m',
    mature_width: '0.8m - 1.2m',
    foliage: 'Tiny aromatic heath-like leaves; dense shrub.',
    flowers: 'Massed pink flowers creating a “supernova” effect in bloom.',
    flowering_time: 'Winter – Spring',
    soil_preference: 'Well-drained sandy or gravelly loam; full sun',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection',
    conservation_description: 'Floriferous thryptomene selection for winter colour and cut flowers.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Thryptomene_saxicola.jpg',
  },
  {
    scientific_name: "Thryptomene saxicola 'F.C. Payne'",
    common_name: 'F.C. Payne Thryptomene',
    genus: 'Thryptomene',
    pretreatment: 'None Required (cutting-grown cultivar)',
    germination: 'Cuttings preferred. Keep humidity high until rooted.',
    growth_rate: 'Moderate',
    mature_height: '0.6m - 1m',
    mature_width: '0.8m - 1.5m',
    foliage: 'Tiny grey-green leaves on arching stems.',
    flowers: 'Soft pink massed flowers along stems.',
    flowering_time: 'Winter – Spring (Jun - Oct)',
    soil_preference: 'Well-drained sandy loam; avoid waterlogging',
    frost_tolerance: 'Moderate (-4°C)',
    drought_tolerance: 'High',
    conservation_status: 'Cultivar',
    conservation_locale: 'Garden / nursery selection (WA affinity)',
    conservation_description: 'Classic Thryptomene saxicola cultivar; long used in Australian gardens and floristry.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Thryptomene_saxicola.jpg',
  },
]

const existingNames = new Set(species.map((s) => s.scientific_name.toLowerCase()))
const added = []
let nextId = Math.max(...species.map((s) => Number(s.legacy_id) || 0)) + 1

for (const plant of NEW_PLANTS) {
  if (existingNames.has(plant.scientific_name.toLowerCase())) {
    console.log('Skip existing:', plant.scientific_name)
    continue
  }
  const image_source = plant.image_url.includes('wikimedia.org') ? 'library_cc' : 'web_link'
  species.push({
    legacy_id: String(nextId++),
    ...plant,
    image_attribution: image_source === 'library_cc' ? 'Wikimedia Commons' : '',
    image_license: image_source === 'library_cc' ? 'See source page' : '',
    image_source,
  })
  existingNames.add(plant.scientific_name.toLowerCase())
  added.push(plant.scientific_name)
}

fs.writeFileSync(speciesPath, JSON.stringify(species, null, 2) + '\n')
console.log(`Added ${added.length} plants (catalog now ${species.length})`)
added.forEach((n) => console.log(' +', n))
